backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use common\helpers\ImportHelper;
use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{


    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Import data for test. Cities and countries from json file /cosole/migrations/data/countries_cities.json
     */
    public function actionImportTest()
    {
        $path = Yii::getAlias("@console/migrations") . DIRECTORY_SEPARATOR . 'data' . DIRECTORY_SEPARATOR . 'countries_cities.json';
        $importResult = ImportHelper::importTestData($path);
        if ($importResult) {
            Yii::$app->session->setFlash("success", "Successful import");
        } else {
            Yii::$app->session->setFlash("success", "Something was wrong on import");
        }
        return $this->redirect(Url::to(["/countries/index"]));
    }

}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use common\models\Cities;
use common\models\ForecastSearch;
use frontend\models\StatsForm;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;


/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Displays stats.
     *
     * @return mixed
     */
    public function actionStats()
    {
        $searchModel = new StatsForm();
        $dataProvider = $searchModel->getContext(Yii::$app->request->queryParams);
        return $this->render('stats', [
            "statsForm" => $searchModel,
            "dataProvider" => $dataProvider,
        ]);
    }

    /**
     * Displays history of a city.
     * @param $city
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionHistory($city)
    {
        $model = Cities::findOne(["name" => $city]);
        if (empty($model)) {
            throw new NotFoundHttpException(Yii::t('admin', 'The requested city does not exist.'));
        }
        $forecasts = new ForecastSearch();
        $forecasts->city_id = $model->id;
        $dataProvider = $forecasts->searchDaily();

        return $this->render('history', [
            "dataProvider" => $dataProvider
        ]);
    }
}

frontend/views/site/_stats_search.php
<?php
/* @var $this yii\web\View
 * @var $statsForm \frontend\models\StatsForm
 */

use kartik\datetime\DateTimePicker;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\web\View;

?>
<div class="panel panel-default">
    <div class="panel-heading">
        <?= Yii::t("client", "Search") ?>
    </div>

    <?php
    $form = ActiveForm::begin([
        "id" => "form-StatsForm",
        "method" => "GET",
        'options' => [
            'data-pjax' => 1
        ],
    ]);
    ?>
    <div class="panel-body row">
        <div class="col-xs-2">
            <?= $form->field($statsForm, 'start')->widget(DateTimePicker::classname(), [
                'options' => ['readonly' => true, 'placeholder' => 'Enter event time ...'],
                'type' => DateTimePicker::TYPE_COMPONENT_APPEND,
                'removeButton' => false,
                'pluginOptions' => ['autoclose' => true, 'format' => 'dd.mm.yyyy', 'minView' => "month"]
            ]); ?>
        </div>
        <div class="col-xs-2">
            <?= $form->field($statsForm, 'end')->widget(DateTimePicker::classname(), [
                'options' => ['readonly' => true, 'placeholder' => 'Enter event time ...'],
                'type' => DateTimePicker::TYPE_COMPONENT_APPEND,
                'removeButton' => false,
                'pluginOptions' => ['autoclose' => true, 'format' => 'dd.mm.yyyy', 'minView' => "month"]
            ]); ?>
        </div>
        <div class="col-xs-2">
            <div class="form-group">
                <?= Html::submitButton('<span class="glyphicon glyphicon-search"></span> ' .
                    Yii::t("client", "Search"), [
                    'class' => 'btn btn-success',
                    'style' => 'margin-top: 25px'
                ]) ?>

            </div>
        </div>
    </div>
    <?php
    ActiveForm::end();
    ?>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/history.php
<?php

/* @var $this yii\web\View */

/* @var $dataProvider \yii\data\ActiveDataProvider */

use common\widgets\HistoryForecast;

$this->title = Yii::t('client', 'History of {city} ({country})', ['city' => 'Moscow', 'country' => 'Russia']);
$this->params['breadcrumbs'][] = ['label' => Yii::t("client", "Statistics"), 'url' => ["/site/stats"]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-history">
    <?= HistoryForecast::widget([
        'title' => $this->title,
        'dataProvider' => $dataProvider
    ]) ?>
</div>

frontend/views/site/stats.php
<?php

/* @var $this yii\web\View
 * @var $statsForm \frontend\models\StatsForm
 * @var $dataProvider \yii\data\ArrayDataProvider
 */

use common\helpers\TemperatureHelper;
use yii\bootstrap\ButtonDropdown;
use yii\grid\GridView;
use yii\widgets\Pjax;

$this->title = Yii::t('client', 'Statistics');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-stats">
    <?php Pjax::begin([
        'id' => 'stats-pjax',
        'timeout' => false,
        'enablePushState' => false,
        'clientOptions' => ['method' => 'GET']
    ]); ?>
    <?= $this->render('_stats_search', [
        'statsForm' => $statsForm,
    ]) ?>
    <div class="panel panel-default">
        <div class="panel-body">
            <?= GridView::widget([
                'id' => 'grid-StatsForm',
                'layout' => "{summary}<div class='pull-right'>{pager}</div>\n{items}\n<div class='pull-right'>{pager}</div>",
                'pager' => [
                    'firstPageLabel' => 'First',
                    'lastPageLabel' => 'Last'
                ],
                'dataProvider' => $dataProvider,
                'columns' => [
                    'country',
                    [
                        "attribute" => "city.name",
                        "label" => Yii::t("client", "City")
                    ],
                    [
                        "attribute" => "max_temperature",
                        "value" => function ($model) {
                            $tempertature = TemperatureHelper::fahrenheit_to_celsius($model["max_temperature"]);
                            if ($tempertature > 0) {
                                return '+' . $tempertature . '&#8451;';
                            }
                            return $tempertature . '&#8451;';

                        },
                        "format" => "raw"
                    ],
                    [
                        "attribute" => "min_temperature",
                        "value" => function ($model) {
                            $tempertature = TemperatureHelper::fahrenheit_to_celsius($model["min_temperature"]);
                            if ($tempertature > 0) {
                                return '+' . $tempertature . '&#8451;';
                            }
                            return $tempertature . '&#8451;';
                        },
                        "format" => "raw"
                    ],
                    [
                        "attribute" => "avg_temperature",
                        "value" => function ($model) {
                            $tempertature = round(TemperatureHelper::fahrenheit_to_celsius($model["avg_temperature"]));
                            if ($tempertature > 0) {
                                return '+' . $tempertature . '&#8451;';
                            }
                            return $tempertature . '&#8451;';
                        },
                        "format" => "raw"
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{all}',
                        'buttons' => [
                            'all' => function ($url, $model, $key) {
                                return ButtonDropdown::widget([
                                    'encodeLabel' => false, // if you're going to use html on the button label
                                    'label' => \Yii::t('client', 'Action'),
                                    'dropdown' => [
                                        'encodeLabels' => false, // if you're going to use html on the items' labels
                                        'items' => [
                                            [
                                                'label' => \Yii::t('client', 'History'),
                                                'url' => ['history', 'city' => $model["city"]["name"]],
                                            ],
                                        ],
                                        'options' => [
                                            'class' => 'dropdown-menu-left', // right dropdown
                                        ],
                                    ],
                                    'options' => [
                                        'class' => 'btn-default',   // btn-success, btn-info, et cetera
                                    ],
                                    'split' => false,    // if you want a split button
                                ]);
                            },
                        ],
                    ],
                ],
            ]); ?>
        </div>
    </div>
    <?php PJax::end() ?>
</div>